[project]
name = "ComfyUI-HandyNodes-KT"
description = "Handy Nodes - GUI INPUTS, Video/Audio Chunking, Prompt looper, Speaker control, etc."
version = "1.2.5"
license = { file = "LICENSE" }

[project.urls]
Repository = "https://github.com/trashkollector/TKNodes"

[tool.comfy]
PublisherId = "trashkollector"
DisplayName = "ComfyUI Handy Nodes"
Icon = ""

